# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1.1 on 2026-09-13 16:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_regional", "0002_reset_pk_sequences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("timezone", models.CharField(default="Europe/Warsaw", max_length=64)),
                ("country", models.CharField(default="PL", max_length=2)),
                (
                    "mode",
                    models.CharField(
                        choices=[("dry_run", "Dry run"), ("sandbox", "Sandbox"), ("live", "Live")],
                        default="dry_run",
                        max_length=16,
                    ),
                ),
                ("sandbox_mailbox", models.EmailField(blank=True, default="", max_length=254)),
                ("live_enabled", models.BooleanField(default=False)),
                (
                    "default_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communicator_default_channels",
                        to="django_regional.language",
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        blank=True, related_name="communicator_channels", to="django_regional.language"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text="e.g. lead.cold.shop",
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9_-]+(\\.[a-z0-9_-]+)*$", "Lower-case dotted key, e.g. lead.cold.shop."
                            )
                        ],
                    ),
                ),
                ("kind", models.CharField(choices=[("static", "Static"), ("ai_prompt", "AI prompt")], max_length=16)),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("body", models.TextField()),
                ("json_schema", models.JSONField(blank=True, null=True)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("requires_legal_footer", models.BooleanField(default=True)),
                ("auto_approve", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="django_communicator.channel",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="django_regional.language"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageTemplateVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField()),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("body", models.TextField()),
                ("json_schema", models.JSONField(blank=True, null=True)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="django_communicator.messagetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="django_communicator.messagetemplateversion",
            ),
        ),
        migrations.CreateModel(
            name="Suppression",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("email", "Email"), ("domain", "Domain")], max_length=16)),
                ("value", models.CharField(max_length=254)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppressions",
                        to="django_communicator.channel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("subject_ref", models.CharField(db_index=True, max_length=200)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("replied", "Replied"), ("closed", "Closed")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="django_communicator.channel",
                    ),
                ),
                (
                    "recipient_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="django_regional.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(choices=[("out", "Outbound"), ("in", "Inbound")], default="out", max_length=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review_required", "Review required"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("suppressed", "Suppressed"),
                            ("would_send", "Would send"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("body_text", models.TextField(blank=True, default="")),
                ("body_html", models.TextField(blank=True, default="")),
                ("render_context", models.JSONField(blank=True, default=dict)),
                ("rendered_prompt", models.TextField(blank=True, default="")),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("usage", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("automated_rewrites", models.PositiveSmallIntegerField(default=0)),
                ("edited_by_human", models.BooleanField(default=False)),
                ("requires_review", models.BooleanField(default=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.CharField(blank=True, default="", max_length=255)),
                ("review_notes", models.TextField(blank=True, default="")),
                ("legal_footer", models.TextField(blank=True, default="")),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("message_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_template", "No template"),
                            ("render", "Render"),
                            ("budget", "Budget"),
                            ("schema", "Schema"),
                            ("model", "Model"),
                            ("upstream", "Upstream"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("failure_detail", models.TextField(blank=True, default="")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="django_communicator.message",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_communicator.messagetemplateversion",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="django_communicator.thread",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="messagetemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "number"), name="communicator_template_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagetemplate",
            constraint=models.UniqueConstraint(
                fields=("channel", "key", "language"), name="communicator_template_unique_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="suppression",
            constraint=models.UniqueConstraint(
                fields=("channel", "kind", "value"), name="communicator_suppression_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["channel", "subject_ref", "recipient_email"], name="communicator_thread_ref_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["status", "created_at"], name="communicator_msg_status_idx"),
        ),
    ]
