# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1.1 on 2026-09-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_communicator", "0002_message_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="send_attempts",
            field=models.PositiveSmallIntegerField(default=0, help_text="SMTP deliveries tried (4xx retries)."),
        ),
        migrations.AlterField(
            model_name="message",
            name="failure_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_template", "No template"),
                    ("render", "Render"),
                    ("budget", "Budget"),
                    ("schema", "Schema"),
                    ("model", "Model"),
                    ("upstream", "Upstream"),
                    ("smtp", "SMTP"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SendPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("business_days_only", models.BooleanField(default=True)),
                ("daily_cap", models.PositiveIntegerField(default=10)),
                (
                    "spread",
                    models.BooleanField(default=True, help_text="Spread the daily cap over the remaining window runs."),
                ),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_policy",
                        to="django_communicator.channel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="django_communicator.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SequenceStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("days_after_previous", models.PositiveSmallIntegerField()),
                ("template_key", models.SlugField(max_length=128)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="django_communicator.sequence",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "number"],
            },
        ),
        migrations.CreateModel(
            name="TextPool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="django_communicator.sequence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadPoolUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="django_communicator.textpool"
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="django_communicator.thread"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreadSequenceState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("step", models.PositiveSmallIntegerField(default=0)),
                ("next_due_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stop_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("replied", "Replied"),
                            ("optout", "Opt-out"),
                            ("bounce", "Bounce"),
                            ("manual", "Manual"),
                            ("finished", "Finished"),
                            ("paused", "Paused"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="django_communicator.sequence"
                    ),
                ),
                (
                    "thread",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequence_state",
                        to="django_communicator.thread",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SendWindow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="windows",
                        to="django_communicator.sendpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["policy", "order", "start_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))), name="sendwindow_end_after_start"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sequence",
            constraint=models.UniqueConstraint(fields=("channel", "key"), name="communicator_sequence_key_unique"),
        ),
        migrations.AddConstraint(
            model_name="sequencestep",
            constraint=models.UniqueConstraint(fields=("sequence", "number"), name="communicator_sequence_step_unique"),
        ),
        migrations.AddConstraint(
            model_name="threadpoolusage",
            constraint=models.UniqueConstraint(fields=("thread", "text"), name="communicator_pool_usage_unique"),
        ),
    ]
