# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1.1 on 2026-09-13 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_communicator.utils.encrypted_field


class Migration(migrations.Migration):
    dependencies = [
        ("django_communicator", "0003_sending"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="bounce_retry_at",
            field=models.DateTimeField(blank=True, help_text="Set by the first soft bounce (4.x.x).", null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="failure_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_template", "No template"),
                    ("render", "Render"),
                    ("budget", "Budget"),
                    ("schema", "Schema"),
                    ("model", "Model"),
                    ("upstream", "Upstream"),
                    ("smtp", "SMTP"),
                    ("bounce", "Bounce"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="MailboxConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("imap_host", models.CharField(max_length=255)),
                ("imap_port", models.PositiveIntegerField(default=993)),
                ("imap_use_ssl", models.BooleanField(default=True)),
                ("imap_user", models.CharField(max_length=255)),
                ("imap_password", django_communicator.utils.encrypted_field.EncryptedTextField(blank=True, default="")),
                ("folder", models.CharField(default="INBOX", max_length=64)),
                ("last_uid", models.PositiveBigIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailbox_config",
                        to="django_communicator.channel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("from_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=998)),
                ("body_text", models.TextField(blank=True, default="")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reply", "Reply"),
                            ("auto", "Autoresponder"),
                            ("suspected_optout", "Suspected opt-out"),
                            ("bounce_hard", "Hard bounce"),
                            ("bounce_soft", "Soft bounce"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "matched_by",
                    models.CharField(
                        choices=[("header", "Header"), ("sender", "Sender"), ("dsn", "DSN")], max_length=16
                    ),
                ),
                ("inbound_message_id", models.CharField(max_length=998, unique=True)),
                ("received_at", models.DateTimeField()),
                ("raw_headers", models.JSONField(blank=True, default=dict)),
                ("optout_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="django_communicator.message",
                    ),
                ),
                (
                    "optout_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="django_communicator.thread",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "replies",
            },
        ),
    ]
