# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.6 on 2026-09-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_communicator", "0004_inbound"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="send_attempted_at",
            field=models.DateTimeField(blank=True, help_text="Wall clock of the `sending` claim.", null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="sequence_step",
            field=models.PositiveSmallIntegerField(blank=True, help_text="Set on sequence follow-ups.", null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="failure_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_template", "No template"),
                    ("render", "Render"),
                    ("budget", "Budget"),
                    ("schema", "Schema"),
                    ("model", "Model"),
                    ("upstream", "Upstream"),
                    ("smtp", "SMTP"),
                    ("bounce", "Bounce"),
                    ("send_outcome_unknown", "Send outcome unknown"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review_required", "Review required"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("suppressed", "Suppressed"),
                    ("would_send", "Would send"),
                    ("rejected", "Rejected"),
                    ("superseded", "Superseded"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="threadsequencestate",
            name="stop_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("replied", "Replied"),
                    ("optout", "Opt-out"),
                    ("bounce", "Bounce"),
                    ("manual", "Manual"),
                    ("finished", "Finished"),
                    ("paused", "Paused"),
                    ("failed", "Failed"),
                    ("suppressed", "Suppressed"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
