# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1.1 on 2026-09-13 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_reply_channel(apps, schema_editor):
    Reply = apps.get_model("django_communicator", "Reply")
    Thread = apps.get_model("django_communicator", "Thread")
    channel = Thread.objects.filter(pk=models.OuterRef("thread_id")).values("channel_id")[:1]
    Reply.objects.update(channel_id=models.Subquery(channel))


class Migration(migrations.Migration):
    dependencies = [
        ("django_communicator", "0005_send_once"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundQuarantine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("uid", models.PositiveBigIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("oversized", "Oversized"),
                            ("unparseable", "Unparseable"),
                            ("data_error", "Data error"),
                        ],
                        max_length=16,
                    ),
                ),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("received_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="mailboxconfig",
            name="uid_validity",
            field=models.PositiveBigIntegerField(blank=True, help_text="UIDVALIDITY the cursor belongs to.", null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="delivery_note",
            field=models.CharField(blank=True, default="", help_text="Last DSN that changed nothing.", max_length=64),
        ),
        migrations.AddField(
            model_name="reply",
            name="channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="django_communicator.channel",
            ),
        ),
        migrations.RunPython(backfill_reply_channel, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="reply",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="django_communicator.channel"
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="inbound_message_id",
            field=models.CharField(max_length=998),
        ),
        migrations.AddConstraint(
            model_name="reply",
            constraint=models.UniqueConstraint(
                fields=("channel", "inbound_message_id"), name="communicator_reply_inbound_uniq"
            ),
        ),
        migrations.AddField(
            model_name="inboundquarantine",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="django_communicator.mailboxconfig"
            ),
        ),
    ]
