# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Generated by Django 6.1.1 on 2026-09-14 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_communicator", "0007_version_sequence_step"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppression",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppressions",
                to="django_communicator.channel",
            ),
        ),
        migrations.AlterField(
            model_name="suppression",
            name="kind",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("domain", "Domain"),
                    ("email_token", "Erased address token (all channels)"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="suppression",
            constraint=models.UniqueConstraint(
                condition=models.Q(("channel__isnull", True)),
                fields=("kind", "value"),
                name="communicator_suppression_global_unique",
            ),
        ),
    ]
